runtime: python311
entrypoint: gunicorn -b :$PORT traintracker.wsgi

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65

env_variables:
  DJANGO_SETTINGS_MODULE: "traintracker.settings"

beta_settings:
  cloud_sql_instances: "wide-approach-403111:us-east1:secondbase"

